name: Validate with HACS

on:
  pull_request:
  push:
    branches: master

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: { "brands" }